### PR TITLE
Message: hostname can be set in constructor, using only $_SERVER['HTT…

### PR DESCRIPTION
**Pull request by ondrs**
…P_HOST'] is insufficient

Gmail pays particularly close attention to Message ID and Received headers. Message IDs that are formed incorrectly (without brackets <> and with wrong domain after @) can make Gmail think you are a spammer.

### CODE REVIEW

**Comment by JanTvrdik** [comment]
Note: the text is a citation from https://help.mailgun.com/hc/en-us/articles/203306870-Does-the-content-of-my-email-matter-for-deliverability

**Comment by dg** [comment]
`__construct($hostname = NULL)` seems weird to me.

**Comment by JanTvrdik** [comment]
@dg Why? If we make the parameter required, it's BC break. That may be acceptable for Nette Mail 3.x but not for Nette Mail 2.4.x

**Comment by hrach** [comment]
@JanTvrdik why not a setter?

**Comment by dg** [comment]
Should not it be the responsibility of the mailer?

**Comment by JanTvrdik** [comment]
> why not a setter?

Because it's currently a hard dependency. The class does not work without hostname (yes, I consider using global variables as *not working*).

Setter is an OK solution for Nette Mail 2.4 but not for Nette Mail 3.x

**Comment by ondrs** [comment]
Here is another proposa. I think hostname can be safely detected from the sender's email address.

**Comment by CZechBoY** [comment]
What about hosting emails? You have email abc@mydomain.com and mx is on mx.myhosting.org

**Comment by ondrs** [comment]
That's why the hostname could and should still be set in the constructor or via its setter.
If no hostname is set, only then it will be detected from the sender's email.

**Pull request closed without merging**
